name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  test_it_data:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run IT Data tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/src  
          pytest tests/test_process_it_data/

  test_marketing_address_info:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Marketing Address Info tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)/src  
          pytest tests/test_process_marketing_address_info/

  black:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install black

      - name: Check code formatting with Black
        run: |
          source venv/bin/activate
          black --check .

  ruff:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install ruff

      - name: Lint code with Ruff
        run: |
          source venv/bin/activate
          ruff check --output-format=github --target-version=py310

      - name: Check code formatting with Ruff
        run: |
          source venv/bin/activate
          ruff format --diff --target-version=py310
        continue-on-error: true
